야스오
Lemon300g/lol pull request #2
Opened 2022-06-11 02:35 UTC by Mapo-Work

[김대리]  야스오 완료

2022-06-11 02:40 UTC, MapoWork2 reviewed
아니 왜 PR 이 이 계정으로와 -_- 자격 증명 때문에 꼬였네보네

2022-06-11 02:44 UTC, Lemon300g reviewed
배포 1.0 버전이 아직 release 가 안되서 최사원 누누 완료하면 그때 승인해줄테니까...
좀 쉬어 이제!! 휴가도 좀 다녀오고!!

2022-06-12 12:30 UTC, Lemon300g requested changes
1. git checkout dev
2. git pull origin dev
3. git checkout feature/yaso
4. git rebase dev
5. git push -f origin feature/yaso
6. PR요청을 새로해

2022-06-12 12:41 UTC, Lemon300g approved these changes

2022-06-12 12:42 UTC, merged